version: "3.9"
services:
  dog-backend:
    build:
      context: .
      args:
        - ARGUMENT_VAR=${example_var}
    container_name: dog-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env_example
    environment:
      - example_var=${example_var}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15
    env_file:
      - .env_example
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
